const fs = require('fs');
const path = require('path');

// Configuration
const POG_PATH = 'C:/Users/Destiny/Desktop/New folder/POG-Ultimate/rsc-data/config';
const DEST_PATH = path.join(__dirname, '../rsc-server/src/constants/ids.js');

function sanitizeName(name) {
    if (!name) return 'UNKNOWN';
    let sanitized = name.toUpperCase()
        .replace(/[^A-Z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');

    // Ensure it starts with a letter or underscore, java/js style (though these are string keys)
    if (/^[0-9]/.test(sanitized)) {
        sanitized = '_' + sanitized;
    }
    return sanitized;
}

function processList(list, typeName) {
    const map = {};
    const nameCounts = {};

    list.forEach((item, index) => {
        try {
            if (!item) {
                console.warn(`Skipping null item at index ${index}`);
                return;
            }

            let name = sanitizeName(item.name);

            // Handle strictly empty/null names in sparse arrays if any
            if (name === 'UNKNOWN' || name === '') {
                name = `UNKNOWN_${typeName}_${index}`;
            }

            if (nameCounts[name]) {
                nameCounts[name]++;
                const uniqueSuffix = (item.model && item.model.id) ? item.model.id : index;
                name = `${name}_${uniqueSuffix}`;

                // If still collision/simple dup, just append index
                if (map[name] !== undefined) {
                    name = `${sanitizeName(item.name)}_${index}`;
                }
            } else {
                nameCounts[name] = 1;
            }

            map[name] = index;
        } catch (e) {
            console.error(`Error processing ${typeName} at index ${index}:`, e);
            console.error('Item:', item);
        }
    });
    return map;
}

function generateFileContent(itemsMap, objectsMap, npcsMap) {
    const printMap = (map, name) => {
        let str = `const ${name} = {\n`;
        for (const [key, value] of Object.entries(map)) {
            str += `    ${key}: ${value},\n`;
        }
        str += '};\n';
        return str;
    };

    return `// Auto-generated by tools/sync-pog-ids.js from POG-Ultimate data
// Do not edit manually if you want to stay in sync with POG-Ultimate

${printMap(itemsMap, 'Items')}
${printMap(objectsMap, 'Objects')}
${printMap(npcsMap, 'Npcs')}

module.exports = { Items, Objects, Npcs };
`;
}

async function main() {
    try {
        console.log('Reading POG-Ultimate data...');
        const items = JSON.parse(fs.readFileSync(path.join(POG_PATH, 'items.json'), 'utf8'));
        const objects = JSON.parse(fs.readFileSync(path.join(POG_PATH, 'objects.json'), 'utf8'));
        const npcs = JSON.parse(fs.readFileSync(path.join(POG_PATH, 'npcs.json'), 'utf8'));

        console.log(`Loaded:
        Items: ${items.length}
        Objects: ${objects.length}
        Npcs: ${npcs.length}`);

        const itemsMap = processList(items, 'ITEM');
        const objectsMap = processList(objects, 'OBJECT');
        const npcsMap = processList(npcs, 'NPC');

        const content = generateFileContent(itemsMap, objectsMap, npcsMap);

        fs.writeFileSync(DEST_PATH, content);
        console.log(`Successfully wrote identifiers to ${DEST_PATH}`);

    } catch (err) {
        console.error('Error syncing IDs:', err);
        process.exit(1);
    }
}

main();
