const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '../');

const ITEM_LIST_PATH = path.join(ROOT, 'openrsc-vanilla/rsc-server/src/plugins/items/item_list.txt');
const ITEMS_JSON_PATH = path.join(ROOT, 'rsc-cloudflare/rsc-server/rsc-data-local/config/items.json');
const IDS_JS_PATH = path.join(ROOT, 'rsc-cloudflare/rsc-server/src/constants/ids.js');

// Helper to sanitize keys for JS constants
const toConstKey = (name) => {
    return name.toUpperCase()
        .replace(/[^A-Z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');
};

const main = () => {
    console.log("Loading Source of Truth: " + ITEM_LIST_PATH);
    if (!fs.existsSync(ITEM_LIST_PATH)) {
        console.error("Source file not found!");
        process.exit(1);
    }

    const itemListRaw = fs.readFileSync(ITEM_LIST_PATH, 'utf8');
    const sourceMap = new Map(); // ID (int) -> Name (string)

    // Parse item_list.txt
    // Format: ItemID = 0 Iron Mace
    const lines = itemListRaw.split(/\r?\n/);
    lines.forEach(line => {
        const match = line.match(/^ItemID\s*=\s*(\d+)\s+(.+)$/);
        if (match) {
            const id = parseInt(match[1], 10);
            const name = match[2].trim();
            sourceMap.set(id, name);
        }
    });

    console.log(`Loaded ${sourceMap.size} items from source of truth.`);

    console.log("Loading Target JSON: " + ITEMS_JSON_PATH);
    const itemsJsonRaw = fs.readFileSync(ITEMS_JSON_PATH, 'utf8');
    let itemsArray = JSON.parse(itemsJsonRaw);

    console.log(`Loaded ${itemsArray.length} items from target items.json.`);

    // Index existing items by Name (lowercase) for lookup
    const existingByName = new Map();
    itemsArray.forEach(item => {
        if (item && item.name) {
            existingByName.set(item.name.toLowerCase(), item);
        }
    });

    const newItemsArray = [];
    const maxID = Math.max(...sourceMap.keys());

    let updatedCount = 0;
    let missingCount = 0;

    for (let i = 0; i <= maxID; i++) {
        const targetName = sourceMap.get(i);

        if (targetName) {
            let itemObj = existingByName.get(targetName.toLowerCase());

            if (!itemObj) {
                // Try fuzzy match or fallback?
                // For now, strict name match or create placeholder
                console.warn(`[WARN] ID ${i}: '${targetName}' not found. Creating placeholder.`);
                itemObj = {
                    name: targetName,
                    description: "Imported from OpenRSC",
                    sprite: 0,
                    price: 1,
                    stackable: false,
                    command: "",
                    equip: [],
                    members: true
                };
                missingCount++;
            } else {
                if (itemObj.name !== targetName) {
                    itemObj.name = targetName;
                }
            }
            newItemsArray[i] = itemObj;
            updatedCount++;
        } else {
            newItemsArray[i] = { name: "Unused", description: "Null item", sprite: 0 };
        }
    }

    console.log(`Reconstructed items array with ${newItemsArray.length} entries.`);
    console.log(`Found ${missingCount} items that needed creation.`);

    // Backup
    fs.writeFileSync(ITEMS_JSON_PATH + '.bak', itemsJsonRaw);

    // Write JSON
    fs.writeFileSync(ITEMS_JSON_PATH, JSON.stringify(newItemsArray, null, 4));
    console.log("Updated items.json");

    // Generate Constants (IDS.JS)
    const constantLines = [];
    constantLines.push("// Auto-generated by tools/sync-items.cjs");
    constantLines.push("const Items = {");

    const usedKeys = new Set();

    newItemsArray.forEach((item, id) => {
        if (!item || !item.name || item.name === "Unused") return;

        let key = toConstKey(item.name);
        if (key === "") return;

        if (usedKeys.has(key)) {
            key = `${key}_${id}`;
        }

        usedKeys.add(key);
        constantLines.push(`    ${key}: ${id},`);
    });

    constantLines.push("};");
    constantLines.push("module.exports = Items;");

    fs.writeFileSync(IDS_JS_PATH, constantLines.join('\n'));
    console.log("Updated ids.js");
};

main();
