const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '../');

const ITEM_LIST_PATH = path.join(ROOT, 'openrsc-vanilla/rsc-server/src/plugins/items/item_list.txt');
const ITEMS_JSON_PATH = path.join(ROOT, 'rsc-cloudflare/rsc-server/rsc-data-local/config/items.json');
const IDS_JS_PATH = path.join(ROOT, 'rsc-cloudflare/rsc-server/src/constants/ids.js');

// Helper to sanitize keys for JS constants
const toConstKey = (name) => {
    return name.toUpperCase()
        .replace(/[^A-Z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');
};

const main = () => {
    console.log("Loading Source of Truth: " + ITEM_LIST_PATH);
    const itemListRaw = fs.readFileSync(ITEM_LIST_PATH, 'utf8');
    const sourceMap = new Map(); // ID (int) -> Name (string)

    // Parse item_list.txt
    // Format: ItemID = 0 Iron Mace
    const lines = itemListRaw.split(/\r?\n/);
    lines.forEach(line => {
        const match = line.match(/^ItemID\s*=\s*(\d+)\s+(.+)$/);
        if (match) {
            const id = parseInt(match[1], 10);
            const name = match[2].trim();
            sourceMap.set(id, name);
        }
    });

    console.log(`Loaded ${sourceMap.size} items from source of truth.`);

    console.log("Loading Target JSON: " + ITEMS_JSON_PATH);
    const itemsJsonRaw = fs.readFileSync(ITEMS_JSON_PATH, 'utf8');
    let itemsArray = JSON.parse(itemsJsonRaw);

    console.log(`Loaded ${itemsArray.length} items from target items.json.`);

    // Index existing items by Name (lowercase) for lookup
    // Optimization: Handle duplicates? 
    // If multiple items have same name in existing JSON, we might grab the first one.
    // Ideally, we want to preserve properties.
    const existingByName = new Map();
    itemsArray.forEach(item => {
        if (item && item.name) {
            existingByName.set(item.name.toLowerCase(), item);
        }
    });

    const newItemsArray = [];
    const maxID = Math.max(...sourceMap.keys());

    // We need to fill the array up to maxID.
    // If user wants "update all", we should probably trim beyond maxID or keep existing if they are higher IDs?
    // "update all item id's to match this list" -> usually implies the list IS the world.

    let updatedCount = 0;
    let missingCount = 0;

    for (let i = 0; i <= maxID; i++) {
        const targetName = sourceMap.get(i);

        if (targetName) {
            // We expect an item with this name at this ID.
            let itemObj = existingByName.get(targetName.toLowerCase());

            if (!itemObj) {
                console.warn(`[WARN] ID ${i}: '${targetName}' not found in existing items.json. Creating placeholder.`);
                itemObj = {
                    name: targetName,
                    description: "Imported from OpenRSC",
                    sprite: 0,
                    price: 1,
                    stackable: false,
                    command: "",
                    equip: [],
                    members: true // Assume members default if new?
                };
                missingCount++;
            } else {
                // We found the detailed object. Use it.
                // update name casing to match source of truth exactly?
                if (itemObj.name !== targetName) {
                    // console.log(`Renaming '${itemObj.name}' -> '${targetName}'`);
                    itemObj.name = targetName;
                }
            }
            newItemsArray[i] = itemObj;
            updatedCount++;
        } else {
            // Gap in source list?
            // If source list has gaps, we should probably put null or a placeholder?
            // JSON arrays can have holes or nulls, but typically games expect contiguous or nulls.
            // Let's explicitly put null if it's a gap.
            // However, items.json usually doesn't have nulls, it indexes by position.
            // Let's create a "Null Item" placeholder to preserve indexing.
            newItemsArray[i] = { name: "Unused", description: "Null item", sprite: 0 };
        }
    }

    console.log(`Reconstructed items array with ${newItemsArray.length} entries.`);
    console.log(`Found ${missingCount} items that needed creation.`);

    // Backup
    fs.writeFileSync(ITEMS_JSON_PATH + '.bak', itemsJsonRaw);

    // Write JSON
    fs.writeFileSync(ITEMS_JSON_PATH, JSON.stringify(newItemsArray, null, 4));
    console.log("Updated items.json");

    // Generate Constants (IDS.JS)
    const constantLines = [];
    constantLines.push("// Auto-generated by tools/sync-items.js");
    constantLines.push("const Items = {");

    // Track keys to avoid duplicates
    const usedKeys = new Set();

    newItemsArray.forEach((item, id) => {
        if (!item || !item.name || item.name === "Unused") return;

        let key = toConstKey(item.name);

        // Handle Collisions
        if (usedKeys.has(key)) {
            let counter = 2;
            let dedupKey = `${key}_${id}`;
            // Simple append ID
            key = dedupKey;
        }

        usedKeys.add(key);
        constantLines.push(`    ${key}: ${id},`);
    });

    constantLines.push("};");
    constantLines.push("module.exports = Items;");

    fs.writeFileSync(IDS_JS_PATH, constantLines.join('\n'));
    console.log("Updated ids.js");
};

main();
