
export const RSC_ASSET_LIST = [
    "1-1dark",
    "1-1light",
    "1-3dark",
    "1-3light",
    "2-1light",
    "2-2dark",
    "2-2light",
    "adamiterock1",
    "altar",
    "animalskull",
    "anvil",
    "ardoungewall",
    "ardoungewallcorner",
    "barpumps",
    "barrel",
    "barrelredcross",
    "barrier1",
    "baxtorianchalice",
    "baxtorianchalicelow",
    "beam",
    "bed",
    "beehive",
    "bench",
    "Bigbed",
    "bigegg",
    "bigroundtable",
    "bigtable",
    "blueflower",
    "blurberrybar",
    "bluriterock1",
    "bookcase",
    "bridge section 1",
    "bridge section 2",
    "bridge section 3",
    "bridge section collapsed",
    "bridge section collapsed2",
    "bridge section corner",
    "brokencart",
    "brokenlograft",
    "brokenpillar",
    "brokenwall",
    "brownclimbingrocks",
    "bullrushes",
    "bush1",
    "bush2",
    "cactus",
    "cactuswatered",
    "candles",
    "carcass",
    "cart",
    "catabow",
    "catabowarrow",
    "cauldron",
    "cave bloodwell",
    "cave bolder",
    "cave bridge stairs",
    "cave bridge support",
    "cave bridge supportbase",
    "cave carvings",
    "cave extra large stagatite",
    "cave furnace",
    "cave grillcage",
    "cave grillcageup",
    "cave grilltrap",
    "cave grilltrapa up",
    "cave grilltrapa",
    "cave large stagamite",
    "cave large stagatite",
    "cave ledge",
    "cave lever",
    "cave old bridge",
    "cave old bridgedown",
    "cave pillar",
    "cave planks",
    "cave platform small",
    "cave platform small2",
    "cave platform verysmall",
    "cave rock1",
    "cave rocktrap1",
    "cave rocktrap1a",
    "cave small stagamite",
    "cave small stagatite",
    "cave smashedcage",
    "cave snaptrap",
    "cave snaptrapa",
    "cave speartrap",
    "cave speartrapa",
    "cave swampbubbles",
    "cave swamprocks",
    "cave temple alter",
    "cave temple",
    "cave templedoor",
    "cave templedooropen",
    "cave tubetrap",
    "cave tubetrapa rope",
    "cave tubetrapa",
    "cave wallgrill",
    "cave well",
    "caveentrance",
    "caveentrance2",
    "ceilingweb",
    "chair",
    "chaosaltar",
    "ChestClosed",
    "ChestOpen",
    "clawsofiban",
    "clawspell1",
    "clawspell2",
    "clawspell3",
    "clawspell4",
    "clawspell5",
    "clayrock1",
    "climbing_rocks",
    "clockpoleblack",
    "clockpoleblue",
    "clockpolepurple",
    "clockpolered",
    "coalrock1",
    "coffin",
    "coffin2",
    "compost",
    "copperrock1",
    "corner_ledge",
    "counter",
    "crate",
    "cupboard",
    "cupboardopen",
    "curvedbone",
    "dangersign",
    "deadtree1",
    "deadtree2",
    "deadtree2base",
    "dolmen",
    "Doormat",
    "doubledoorframe",
    "doubledoorsclosed",
    "doubledoorsopen",
    "dramentree",
    "dugupsoil1",
    "dugupsoil2",
    "dugupsoil3",
    "dwarf multicannon part1",
    "dwarf multicannon part2",
    "dwarf multicannon part3",
    "dwarf multicannon",
    "eggs",
    "elventomb",
    "ent",
    "fallentree",
    "fern",
    "firea1",
    "firea2",
    "firea3",
    "fireplacea1",
    "fireplacea2",
    "fireplacea3",
    "firespell1",
    "firespell2",
    "firespell3",
    "fishing",
    "fishingcrane",
    "fishingcranerot1",
    "fishingcranerot2",
    "flax",
    "floorweb",
    "flower",
    "Foodtrough",
    "fountain",
    "fourwayplatform-lev 0",
    "fourwayplatform-lev 1",
    "furnace",
    "gallows",
    "gemrock",
    "giantcrystal",
    "glarialsstatue",
    "gnomecage",
    "gnomefence",
    "gnomefence2",
    "gnomeglider",
    "gnomeglidercrashed",
    "gnomegoal",
    "gnomehamek",
    "gnomesign",
    "gnomewatchtower lev0",
    "gnomewatchtower lev1",
    "gnomewatchtower lev2",
    "goldrock1",
    "grand tree-lev 0",
    "grand tree-lev 1",
    "grand tree-lev 2",
    "grand tree-lev 3",
    "grand treeinside-lev 0",
    "grand treeinside-lev 1",
    "grand treeinside-lev 2",
    "gravestone1",
    "gravestone2",
    "guthixstone",
    "halfburiedskeleton",
    "halfburiedskeleton2",
    "hazeeltomb",
    "henge",
    "hillsidedoor",
    "hole",
    "hornedskull",
    "ironrock1",
    "jungle fern textured 2",
    "jungle fern textured 3",
    "jungle fern textured 4",
    "jungle fern textured",
    "jungle fern",
    "jungle fly trap",
    "jungle medium size plant",
    "jungle spikey fern",
    "jungle statue",
    "jungle strange plant 2",
    "jungle strange plant",
    "jungle tree 1",
    "jungle tree 2",
    "khazardwall",
    "ladder",
    "ladderdown",
    "landscape",
    "largebone",
    "largegrave",
    "largesewerpipe",
    "largetreeplatformhigh",
    "largetreeplatformlow",
    "largeurn",
    "leverbracket",
    "leverdown",
    "leverup",
    "liftbed",
    "liftwinch",
    "lightning1",
    "lightning2",
    "lightning3",
    "log_balance1",
    "log_balance2",
    "logbridge lev0",
    "logbridge lev1",
    "logbridge lev2",
    "logbridgecurvedhigh",
    "logbridgecurvedlow",
    "logbridgehigh",
    "logbridgejunction lev0",
    "logbridgejunction lev1",
    "logbridgelow",
    "logpile",
    "lograft",
    "longtable",
    "madmachine",
    "magearena colomn",
    "magearena corner",
    "magearena cornerfill",
    "magearena door",
    "magearena plain wall",
    "magearena tallcorner",
    "magearena tallwall",
    "magearena wall",
    "magictree",
    "manholeclosed",
    "manholeopen",
    "mapletree",
    "marblearch",
    "marblepillar",
    "market",
    "metalgateclosed",
    "metalgateclosed2",
    "metalgateopen",
    "metalgateopen2",
    "mill",
    "millbase",
    "milltop",
    "minecart",
    "mithrilrock1",
    "mossyrock",
    "mudpatch",
    "mudpile",
    "mudpiledown",
    "mushroom",
    "nastyfungus",
    "oaktree",
    "obelisk",
    "obstical_frame",
    "obstical_net",
    "obstical_pipe",
    "obstical_ropeswing",
    "ogre standard",
    "palm",
    "palm2",
    "pipe&drain",
    "poorbed",
    "portrait",
    "potato",
    "potteryoven",
    "potterywheel",
    "rams skull door",
    "rams skull dooropen",
    "range",
    "rock cake counter",
    "rock3",
    "rockcounter",
    "rockpool",
    "rockpoolwater",
    "rocks1",
    "rocks2",
    "rocksteps",
    "rocktile",
    "ropeforclimbingbot",
    "ropeladder",
    "roundtable",
    "rowboat",
    "rowboatsinking",
    "runiterock1",
    "sacks",
    "sandpit",
    "sandyfootsteps",
    "saradominstone",
    "Scaffoldsupport",
    "ScaffoldsupportRope",
    "sewervalve",
    "Shamancave",
    "Shipback",
    "Shipfront",
    "shipleak",
    "shipleak2",
    "Shipmiddle",
    "shipspray1",
    "shipspray2",
    "shopsign",
    "signpost",
    "signpost2",
    "silverrock1",
    "sink",
    "sinkingbarrel",
    "sinkingshipfront",
    "skeletonwithbag",
    "skulltorcha1",
    "skulltorcha2",
    "skulltorcha3",
    "skulltorcha4",
    "small caveentrance2",
    "smallfern",
    "smashedchair",
    "smashedtable",
    "spearwall",
    "Spellcharge1",
    "spellcharge2",
    "spellcharge3",
    "spellshock",
    "spikedpit-low",
    "spikedpit",
    "spinningwheel",
    "stalagmites",
    "stonedisc",
    "stonestairs",
    "stonestairsdown",
    "stonestand",
    "stool",
    "straight_ledge",
    "supportnw",
    "sworddummy",
    "table",
    "target",
    "telescope",
    "throne",
    "tinrock1",
    "toplesstree",
    "torcha1",
    "torcha2",
    "torcha3",
    "torcha4",
    "totemtree1",
    "totemtree2",
    "totemtree3",
    "totemtree4",
    "totemtree5",
    "totemtreeevil",
    "totemtreegood",
    "totemtreerotten2",
    "totemtreerotten3",
    "totemtreerotten4",
    "totemtreerotten5",
    "trackbuffer",
    "trackcurve",
    "trackpoints",
    "trackstraight",
    "trawlernet-l",
    "trawlernet-r",
    "trawlernet",
    "tree_for_rope",
    "tree_with_rope",
    "tree_with_vines",
    "tree",
    "tree2",
    "treeplatformhigh",
    "treeplatformhigh2",
    "treeplatformlow",
    "treeplatformlow2",
    "treeroot1",
    "treeroot2",
    "treestump",
    "tribalstature",
    "vine",
    "vinecorner",
    "vinejunction",
    "wallbench",
    "wallclockface",
    "wallgrill",
    "wallpipe",
    "wallpost",
    "wallshield",
    "watchtower",
    "waterfall",
    "waterfalllev1",
    "waterfalllev2",
    "well",
    "wheat",
    "willowtree",
    "windmillsail",
    "woodengateclosed",
    "woodengateopen",
    "woodenrailing",
    "woodenstairs",
    "woodenstairsdown",
    "yewtree",
    "zamorakstone",
    "zodiac"
];
